### ISSUE TITLE
Local server does not verify $PATH env variable on Mac

### ISSUE THREAD

**Issue by VanDulti** [GNS3/gns3-server#2306]
I have a similar problem to #1655 

If gns3-server is started by the GUI, the path is not loaded correctly.
Calling curl -X GET "http://127.0.0.1:3080/v2/compute/qemu/binaries" will return only the three bundled qemu binaries.

If I however start the server by executing /Applications/GNS3.app/Contents/MacOS/gns3server, it works and my custom binaries are loaded correctly.

Any idea why this might be on Mac? Setup: Local Server that boots up with the gu

**Comment by grossmj** [comment]
Thanks, I fixed this. The local server started by the GUI will get $PATH.

**Comment by VanDulti** [comment]
> Thanks, I fixed this. The local server started by the GUI will get $PATH.

Will this be in the next release, and if so, when would that be approximately?

**Comment by grossmj** [comment]
> Will this be in the next release, and if so, when would that be approximately?

Version 2.2.44 should be released within the next 2 weeks.

**Comment by VanDulti** [comment]
> > Will this be in the next release, and if so, when would that be approximately?
> 
> Version 2.2.44 should be released within the next 2 

Still not working, even in the newest version. Can you provide any update on this?

**Comment by grossmj** [comment]
> Still not working, even in the newest version. Can you provide any update on this?

Please give it a try with v2.2.45 and let me know if the problem is still there. Thanks 👍

**Comment by VanDulti** [comment]
Doesn't work with v2.2.45.

![image](https://github.com/GNS3/gns3-server/assets/74293813/bb38c6a3-4f3e-4076-8e19-e1f46a8fa3b0)

**Comment by grossmj** [comment]
Strange. How have you installed your custom Qemu executables?

Can you execute one of the binary from the terminal? For instance `qemu-system-i386 -version -nographic`

Do you see anything in `~/.config/GNS3/2.2/gns3_server.log` after `curl -X GET "http://127.0.0.1:3080/v2/compute/qemu/binaries"`

Thanks.

**Comment by VanDulti** [comment]
When starting gns3server manually, gns3 shows the following (correct) output... strange indeed

![image](https://github.com/GNS3/gns3-server/assets/74293813/667b828b-ce6b-4c7b-989b-3fe9772363dd)

**Comment by grossmj** [comment]
I can reproduce the problem, for some reason the GNS3.app doesn't get the full PATH environment variable. Please try to open the app from the terminal: `open -a /Applications/GNS3.app`, it worked for me.

**Comment by grossmj** [comment]
I did some research, looks like the best way is to configure launchctl to add custom paths. Start a terminal and type the following command.

`sudo launchctl config user path $PATH`

Then reboot as instructed and GNS3.app should see your homebrew Qemu executables. Please let me know if it works on your side. Thanks 👍
