### ISSUE TITLE
GNS3 v1.5: vi shuts the container console

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-server#476]
vi editor causes the container console to shut and cannot open it again, only after restarting:

> 2016-04-04 11:41:16 DEBUG telnet_server.py:245 Unhandled WILL telnet command: 0xff 0xfb 0x0
> 2016-04-04 11:45:49 DEBUG telnet_server.py:245 Unhandled WILL telnet command: 0xff 0xfb 0x0
> 2016-04-04 12:04:18 DEBUG telnet_server.py:245 Unhandled WILL telnet command: 0xff 0xfb 0x0

No such issue from attached console using **docker attach <cid>**

**Comment by ehlers** [comment]
I have no such issues with vi, neither with the alpine/busybox vi nor with debians vim.tiny . I get a one-time
`2016-04-04 16:27:21 DEBUG telnet_server.py:245 Unhandled WILL telnet command: 0xff 0xfb 0x0`
but that doesn't has a negative influence.

**Comment by noplay** [comment]
Same here, which terminal are you using and which container?

**Comment by AJNOURI** [comment]
Gnome-terminal
Maybe vi is the symptom and the root issue lies somewhere else.

![gns3-1 5-docker-vi](https://cloud.githubusercontent.com/assets/1716020/14267903/18ac048e-fad5-11e5-88e8-015e1aca553a.gif)

**Comment by ehlers** [comment]
Normally I use OS X for the GUI. Just repeated my tests with debian linux and gnome-terminal. No problems with alpine/busybox vi and debian:jessie vim-tiny.

**Comment by grossmj** [comment]
I could see a glib warning in your animated gif but it was too quick to see what is it exactly.

**Comment by AJNOURI** [comment]
This happens with **phusion/baseimage** containers (I wasn't experiencing such issues).
Here is the glib warning, I didn't pay attention to it, because it was harmless:

> Starting telnet console in thread "gnome-terminal -t "%d" -e "telnet %h %p""
> 
> (gnome-terminal:28403): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.

**Comment by noplay** [comment]
For the warning it's nothing I think since we don't support it we reply to the client to turn a specific feature  off.

What do you see if you start the command by hand by typing telnet in a terminal?

You don't have a ~/.telnetrc that could change telnet command behavior?

**Comment by noplay** [comment]
I didn't manage to replicate it with the same image.

**Comment by AJNOURI** [comment]
Same from the command line:

> ajn:~$ telnet localhost 2020
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> 
> root@ajnouri/dockervpc-1:/# vi
> Connection closed by foreign host.
> ajn:~$ 
 
I don't have ~/.telnetrc

**Comment by noplay** [comment]
Is it possible to capture with wireshark the telnet session and share the
pcap?

Thanks a lot for the help

**Comment by AJNOURI** [comment]
Here is the file:
http://hpnouri.free.fr/misc/telnet-to-container.pcapng

![image](https://cloud.githubusercontent.com/assets/1716020/14320186/6a44c93a-fc14-11e5-9f8c-f1b434b2924b.png)

**Comment by noplay** [comment]
Seem the client send \r has carriage return I see  that with my client:[image:
Capture d’écran 2016-04-06 à 18.58.48.png]

**Comment by noplay** [comment]
I think I fixed it. Could test and confirm?

Thanks a lot for the help

**Comment by noplay** [comment]
It's pushed

**Comment by AJNOURI** [comment]
Cloned 1.5 branches, still there:

> 2016-04-07 17:38:48 INFO telnet_console.py:97 Starting telnet console in thread "gnome-terminal -t "%d" -e "telnet %h %p""
> 
> (gnome-terminal:31954): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
> 2016-04-07 17:38:48 DEBUG project.py:382 Event received: {'event': {'memory_usage_percent': 43.7, 'cpu_usage_percent': 11.4}, 'action': 'ping'}
> 2016-04-07 17:38:53 DEBUG project.py:382 Event received: {'event': {'memory_usage_percent': 43.7, 'cpu_usage_percent': 4.9}, 'action': 'ping'}
> 2016-04-07 17:38:54 INFO telnet_console.py:82 Telnet console 127.0.0.1:2012 closed

**Comment by noplay** [comment]
Strange I just setup a new linux box. No problem :(

**Comment by AJNOURI** [comment]
Tested right after new GNS3 installation on both on a new virtual machine of another host and a new machine and vi still crashes the telnet session.
Looks like a container image issue (ajnouri/dockervpc) because I have tried a new phusion/base-image container with only vi and it didn't crash telnet.
It is too esoteric issue. I'll check it closer, feel free to close the ticket.
Thanks for your patience Julien

**Comment by noplay** [comment]
Ok you can also send me the Dockerfile if you want.

**Comment by AJNOURI** [comment]
Here is the file https://github.com/AJNOURI/DockerVPC/blob/master/Dockerfile , it needs to loose weight.

**Comment by noplay** [comment]
Impossible to build it's freeze at:
Setting up dbus-x11 (1.6.18-0ubuntu4.3) ...
Setting up udisks2 (2.1.3-1ubuntu0.1) ...
Setting up gvfs-daemons (1.20.3-0ubuntu1.2) ...
Setting up gvfs:amd64 (1.20.3-0ubuntu1.2) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up policykit-1 (0.105-4ubuntu3.14.04.1) ...
Setting up colord (1.0.6-1) ...
Setting up policykit-1-gnome (0.105-1ubuntu4) ...
Setting up libnss3-nssdb (2:3.21-0ubuntu0.14.04.2) ...
Setting up libnss3:amd64 (2:3.21-0ubuntu0.14.04.2) ...
Setting up ca-certificates-java (20130815ubuntu1) ...
